#ifndef MXDM_MXERRORDEF_H_
#define MXDM_MXERRORDEF_H_



#define MD_OK		0x01
#define MD_FAILED	0x00

#define	MD_ERROR_UNKNOWN	1000
#define MD_ERROR_CLIENTFULL	1001
#define MD_ERROR_UNKNOWNISSUE		1002

/////////////Common tree ///////////////

#define MD_ERROR_NOFINDPAGE				5
#define MD_ERROR_KEYISEMPTY				6
#define MD_ERROR_NOFINDRECORD			7
#define MD_ERROR_NOFINDNODE				8
#define MD_ERROR_NOFINDPROPERTY			MD_ERROR_NOFINDRECORD
#define MD_ERROR_DELETEFAILED			9
#define MD_ERROR_NODENAMEISEMPTY		10
#define MD_ERROR_TREENOTOPEN			11
#define MD_ERROR_CREATEOBJ				12
#define MD_ERROR_MAINKEYNOEXIST			13
#define MD_ERROR_SUBKEYNOEXIST			14
#define MD_ERROR_APPENDPROPERTY			15
#define MD_ERROR_KEYALREADYEXIST		16
#define MD_ERROR_FLAGUNKNOW				17
#define MD_ERROR_OVERMAXKEYNAME			18
#define MD_ERROR_PROPERTYALREADYEXIST	19
#define MD_ERROR_FLAGERROR				20
#define MD_ERROR_IMPORTDATAERROR		40
#define MD_ERROR_IMPORTDATAFORMAT		41
#define MD_ERROR_IMPORTPATHEMPTY		42
#define MD_ERROR_IMPORTPARSEPATH		43
#define MD_ERROR_IMPORTADDSUBNODE		44
#define MD_ERROR_EXPORTDATAOVERBUFFER	45
#define MD_ERROR_EXPORTSHARINGCONFLICT	46
#define MD_ERROR_EXPORTFILEALREADYEXIST	47
#define MD_ERROR_IMPORTFILENOFIND		48
#define MD_ERROR_EXPORTCREATEFILE		49
#define MD_ERROR_IMPORTOPENFILE			50
#define MD_ERROR_READONLYKEY			51
#define MD_ERROR_NOAUTHORITY_CREATEMAINKEY		52
#define MD_ERROR_NOAUTHORITY_CREATESYSTEMKEY	53
#define MD_ERROR_NOAUTHORITY_DELETEMAINKEY		54
#define MD_ERROR_OVERMAXEXPORTKEY		55



//////////////////////////////////////////
#define MD_ERROR_OVERBUFFER				100
#define MD_ERROR_COPYPAGEDATA			101
#define MD_ERROR_PARAMETER				102
#define MD_ERROR_INVAILDPARAMETER		103
#define MD_ERROR_BUFFERTOOSMALL			104
#define MD_ERROR_TCPCONNECTFAILED		105
#define MD_ERROR_NEWOBJECTFAILED		106
#define MD_ERROR_COMMUNICATIONFAILED	107
#define MD_ERROR_PROTOCOLERROR			108
#define MD_ERROR_INVALIDHANDLE			109
#define MD_ERROR_ALLOCMEMORYFAILED		110
#define MD_ERROR_GETRAWDATA				111
#define MD_ERROR_CHECKSUM				112
#define MD_ERROR_VERSION				113
#define MD_ERROR_NOFINDFILE				120
#define MD_ERROR_FILESIZEOVERMAX		121
#define MD_ERROR_OPENFILE				122
#define MD_ERROR_MAPFILE				123
#define MD_ERROR_FILESIZEISZERO			124
#define MD_ERROR_FILEALREADYEXIST		125
#define MD_ERROR_CREATEFILE				126
#define MD_ERROR_DATAFOMAT				127

///////////////////DB/////////////////////
#define MD_ERROR_DBHASEXIST				200
#define MD_ERROR_TABLEHASEXIST			201
#define MD_ERROR_TABLENOEXIST			202
#define MD_ERROR_DBNOEXIST				203
#define MD_ERROR_INVALIDFLAG			204
#define MD_ERROR_INVALIDDBNAME			205
#define MD_ERROR_GETFIELDSBUFFER		206
#define MD_ERROR_NOFIELD				207
#define MD_ERROR_FIELDDATAERROR			208
#define MD_ERROR_INVALIDFIELD			209
#define MD_ERROR_NOFINDTABLERECORD		210
#define MD_ERROR_INVALIDCONDITION		221
#define MD_ERROR_FIELDVALUENOMATCH		211
#define MD_ERROR_CREATEFIELDSERROR		212
#define MD_ERROR_INVALIDRECORDSET		213
#define MD_CURSOR_END					214
#define MD_CURSOR_BEGIN					215
#define MD_ERROR_CREATERECORD			216
#define MD_ERROR_PARSERECORD			217
#define MD_ERROR_DATAFORMAT				218
#define MD_ERROR_ISNOTDYNTABLE			219
#define MD_ERROR_DYNISEMPTY				220

//////////////////MQ//////////////////////

#define MD_ERROR_MQNOINITIALIZATION		230
#define MD_ERROR_MQNOEXIST				231
#define MD_ERROR_PASSWORDERROR			232
#define MD_ERROR_MQHASEXIST				234
#define MD_QUEUE_EMPTY					235
#define MD_ERROR_TIMEOUT				236
#define MD_ERROR_RETURNDATATYPEERROR	237
#define MD_ERROR_NOFINDSUITMQ			238
#define MD_ERROR_ATLEASTONEERROR		239

////////////////dog///////////////////////
#define MD_ERROR_INITDOGFAILED			300
#define MD_ERROR_READDOGFAILED			301

/////////////////other////////////////////

#define MD_MXMC_NORUNNING				400
#define MD_MXMC_RUNNING					401




#endif